version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    volumes:
      - /tmp/docker-registry:/var/lib/registry
    restart: unless-stopped
    networks:
      - docker-webui-network

  webui:
    build: .
    container_name: docker-webui
    ports:
      - "8501:8501"
    volumes:
      # Use the correct Docker socket path for this system
      - /run/docker.sock:/var/run/docker.sock
      # Alternative paths if the above doesn't work
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /var/snap/docker/common/run/docker.sock:/var/run/docker.sock
      - /tmp/docker-webui:/tmp/docker-webui
      - .:/app
    environment:
      - REGISTRY_URL=registry:5000
    depends_on:
      - registry
    networks:
      - docker-webui-network

networks:
  docker-webui-network:
    driver: bridge
